version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - "4000:4000"
    depends_on:
      - auth
      - notes
  auth:
    build: ./auth
    expose:
      - "3000"
  notes:
    build: ./notes
    expose:
      - "3001"